places_to_see = []
places_to_see.append('mexico')
places_to_see.append('spain')
places_to_see.append('costa rica')
places_to_see.append('australia')
places_to_see.append('united kingdom')
print(places_to_see)
print(sorted(places_to_see))
print(places_to_see)
print(sorted(places_to_see, reverse=True))
print(places_to_see)
places_to_see.reverse()
print(places_to_see)
places_to_see.reverse()
print(places_to_see)
places_to_see.sort()
print(places_to_see)
places_to_see.sort(reverse=True)
print(places_to_see)
